### ISSUE TITLE
Size limit on messages

### ISSUE THREAD

**Issue by niteshmor** [niteshmor/routia#1]
Issues with large GDP PDU's because of twisted's underlying buffers. For example, sending a message of size around 66,000 bytes, the following happens:

```python
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "./routia.py", line 135, in process_received_data
    raise UnrecognizedFormat
__main__.UnrecognizedFormat: 
```

**Comment by niteshmor** [comment]
Fixed with commit d326f39c25d6c4e8724b69d4fd0d274b3589cc05
